"""initial_migration

Revision ID: ede61c24ee1e
Revises: 
Create Date: 2026-06-16 16:32:49.506119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede61c24ee1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('chronology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=10000), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chronology', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chronology_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_chronology_id'), ['id'], unique=False)

    op.create_table('dashboard',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('extra_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('dialectics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dialectics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialectics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dialectics_title'), ['title'], unique=False)

    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('important', sa.Boolean(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('recurrence_id', sa.String(length=50), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=100), nullable=True),
    sa.Column('recurrence_end', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_position'), ['position'], unique=False)

    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habits_read'), ['read'], unique=False)

    op.create_table('habits_done',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('countdays', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habits_done', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habits_done_id'), ['id'], unique=False)

    op.create_table('language_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('rule_ru', sa.Text(), nullable=True),
    sa.Column('rule_en', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('language_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_rule_id'), ['id'], unique=False)

    op.create_table('note_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('note_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_category_id'), ['id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_is_pinned'), ['is_pinned'], unique=False)

    op.create_table('recurrence_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurrence_id', sa.String(length=50), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurrence_exception', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurrence_exception_exception_date'), ['exception_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrence_exception_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrence_exception_recurrence_id'), ['recurrence_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_done'), ['done'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_position'), ['position'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('wink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wink', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wink_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_wink_id'), ['id'], unique=False)

    op.create_table('word_shows_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shows_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_shows_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_shows_daily_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_word_shows_daily_id'), ['id'], unique=False)

    op.create_table('word_stats',
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_shown', sa.DateTime(), nullable=False),
    sa.Column('eng', sa.String(length=100), nullable=True),
    sa.Column('de', sa.String(length=100), nullable=True),
    sa.Column('it', sa.String(length=100), nullable=True),
    sa.Column('ru', sa.String(length=200), nullable=True),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('is_known_en', sa.Boolean(), nullable=False),
    sa.Column('is_known_it', sa.Boolean(), nullable=False),
    sa.Column('is_known_de', sa.Boolean(), nullable=False),
    sa.Column('is_learned', sa.Boolean(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=True),
    sa.Column('knowledge_stats', sa.JSON(), nullable=True),
    sa.Column('show_stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('word')
    )
    with op.batch_alter_table('word_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_stats_is_learned'), ['is_learned'], unique=False)

    op.create_table('word_stats_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('imw', sa.Float(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('fully_learned_count', sa.Integer(), nullable=False),
    sa.Column('test_total', sa.Integer(), nullable=False),
    sa.Column('test_success', sa.Integer(), nullable=False),
    sa.Column('test_stats_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('word_stats_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_stats_snapshot_id'), ['id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=True),
    sa.Column('no_time', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_id'), ['id'], unique=False)

    op.create_table('sticky_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('recurrence_id', sa.String(length=50), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('habit_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('dialectics_id', sa.Integer(), nullable=True),
    sa.Column('dialectics_block_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dialectics_id'], ['dialectics.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sticky_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sticky_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sticky_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sticky_notes_position'), ['position'], unique=False)

    op.create_table('observation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observation_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_logs_done_at'), ['done_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_logs_observation_id'), ['observation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('observation_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_logs_observation_id'))
        batch_op.drop_index(batch_op.f('ix_observation_logs_id'))
        batch_op.drop_index(batch_op.f('ix_observation_logs_done_at'))

    op.drop_table('observation_logs')
    with op.batch_alter_table('sticky_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sticky_notes_position'))
        batch_op.drop_index(batch_op.f('ix_sticky_notes_id'))
        batch_op.drop_index(batch_op.f('ix_sticky_notes_created_at'))

    op.drop_table('sticky_notes')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_id'))
        batch_op.drop_index(batch_op.f('ix_observations_created_at'))

    op.drop_table('observations')
    with op.batch_alter_table('word_stats_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_stats_snapshot_id'))

    op.drop_table('word_stats_snapshot')
    with op.batch_alter_table('word_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_stats_is_learned'))

    op.drop_table('word_stats')
    with op.batch_alter_table('word_shows_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_shows_daily_id'))
        batch_op.drop_index(batch_op.f('ix_word_shows_daily_date'))

    op.drop_table('word_shows_daily')
    with op.batch_alter_table('wink', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wink_id'))
        batch_op.drop_index(batch_op.f('ix_wink_date'))

    op.drop_table('wink')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_position'))
        batch_op.drop_index(batch_op.f('ix_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_done'))
        batch_op.drop_index(batch_op.f('ix_task_created_at'))

    op.drop_table('task')
    with op.batch_alter_table('recurrence_exception', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurrence_exception_recurrence_id'))
        batch_op.drop_index(batch_op.f('ix_recurrence_exception_id'))
        batch_op.drop_index(batch_op.f('ix_recurrence_exception_exception_date'))

    op.drop_table('recurrence_exception')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_notes_id'))
        batch_op.drop_index(batch_op.f('ix_notes_created_at'))

    op.drop_table('notes')
    with op.batch_alter_table('note_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_category_id'))

    op.drop_table('note_category')
    with op.batch_alter_table('language_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_rule_id'))

    op.drop_table('language_rule')
    with op.batch_alter_table('habits_done', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_done_id'))

    op.drop_table('habits_done')
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_read'))
        batch_op.drop_index(batch_op.f('ix_habits_id'))

    op.drop_table('habits')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_position'))
        batch_op.drop_index(batch_op.f('ix_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_done'))
        batch_op.drop_index(batch_op.f('ix_event_date'))

    op.drop_table('event')
    with op.batch_alter_table('dialectics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialectics_title'))
        batch_op.drop_index(batch_op.f('ix_dialectics_id'))

    op.drop_table('dialectics')
    op.drop_table('dashboard')
    with op.batch_alter_table('chronology', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chronology_id'))
        batch_op.drop_index(batch_op.f('ix_chronology_date'))

    op.drop_table('chronology')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
