"""add_dialectics_category

Revision ID: f65773643b91
Revises: ede61c24ee1e
Create Date: 2026-06-24 16:39:38.683358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65773643b91'
down_revision: Union[str, None] = 'ede61c24ee1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialectics_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dialectics_category')),
    sa.UniqueConstraint('name', name=op.f('uq_dialectics_category_name'))
    )
    with op.batch_alter_table('dialectics_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dialectics_category_id'), ['id'], unique=False)

    with op.batch_alter_table('dialectics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        # Note: We skip altering content_json because we only want to add category_id
        batch_op.create_foreign_key(batch_op.f('fk_dialectics_category_id_dialectics_category'), 'dialectics_category', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dialectics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dialectics_category_id_dialectics_category'), type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('dialectics_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dialectics_category_id'))

    op.drop_table('dialectics_category')
    # ### end Alembic commands ###
