
import json
import os

locales = {
    "en": {
        "title": "ℹ️ Demo Mode:",
        "description": "This is a temporary demonstration session. Your data is stored only in the server's volatile memory and is isolated from other users. All notes and progress will be completely wiped once you close your browser or the server restarts.",
        "ai_note": "Note: Translations to other languages were generated by AI.",
        "button": "Got it"
    },
    "ru": {
        "title": "ℹ️ Демо-режим:",
        "description": "Это временная демонстрационная сессия. Ваши данные хранятся только в оперативной памяти сервера и изолированы от других пользователей. Все заметки и прогресс будут полностью удалены после закрытия браузера или перезапуска сервера.",
        "ai_note": "Примечание: Перевод на другие языки осуществлен ИИ.",
        "button": "Понятно"
    },
    "kz": {
        "title": "ℹ️ Демо-режим:",
        "description": "Бұл уақытша демонстрациялық сессия. Сіздің деректеріңіз тек сервердің жедел жадында сақталады және басқа пайдаланушылардан оқшауланған. Браузерді жапқанда немесе сервер қайта іске қосылғанда барлық жазбалар мен прогресс толығымен жойылады.",
        "ai_note": "Ескертпе: Басқа тілдерге аударманы ЖИ (AI) жасады.",
        "button": "Түсіндім"
    }
}

for lang, data in locales.items():
    file_path = f"d:/Библиотека/Исследования/Искусственный интеллект/papanda/papanda v 0.6.1 experiment/fastapi_app/locales/{lang}.json"
    if os.path.exists(file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            content = json.load(f)
        
        content["demo_banner"] = data
        
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(content, f, ensure_ascii=False, indent=4)
        print(f"Updated {lang}.json")

