name: Build Papanda Mac

# ТРИГГЕРЫ
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    # ШАГ 1: Клонирование кода
    - name: Checkout Code
      uses: actions/checkout@v4

    # ШАГ 2: Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # ШАГ 3: Установка библиотек
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # ШАГ 4: Сборка
    - name: Build with PyInstaller
      run: |
        # В macOS разделитель для add-data это двоеточие (:)
        pyinstaller --onefile --noconsole --hidden-import aiosqlite --hidden-import jinja2 --hidden-import email_validator --hidden-import passlib.handlers.bcrypt --hidden-import cryptography --exclude-module tkinter --add-data "fastapi_app/templates:fastapi_app/templates" --add-data "fastapi_app/static:fastapi_app/static" --add-data "data/resources:data/resources" --name Papanda run_fastapi.py

    # ШАГ 5: Архивация
    # macOS создает папку .app, которую нельзя просто так скачать.
    # Пакуем её в ZIP.
    - name: Zip Application
      run: |
        cd dist
        zip -r Papanda-Mac.zip Papanda.app

    # ШАГ 6: Загрузка результата
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Papanda-Mac-App
        path: dist/Papanda-Mac.zip
