name: Build Papanda EXE

# ТРИГГЕРЫ
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # ШАГ 1: Клонирование кода
    - name: Checkout Code
      uses: actions/checkout@v4

    # ШАГ 2: Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # ШАГ 3: Библиотеки
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Устанавливаем зависимости из файла (если он есть)
        pip install -r requirements.txt
        # Доустанавливаем то, чего может не быть в requirements
        pip install pyinstaller pywebview Pillow

    # ШАГ 4: Сборка
    - name: Build with PyInstaller
      run: |
        # Убедитесь, что файл в репозитории называется именно так (Papanda.spec)
        pyinstaller Papanda.spec

    # ШАГ 5: Сохранение результата
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Papanda-App
        # Важно: PyInstaller создаст файл с именем, указанным в spec (Papanda.exe)
        path: dist/Papanda.exe
